### ISSUE TITLE
Error parsing payload for GET requests that have no content...

### ISSUE THREAD

**Issue by mfedorov** [mulesoft-consulting/json-logger#5]
Failed parsing field: content
org.mule.runtime.core.api.expression.ExpressionRuntimeException: "Unexpected end-of-input at payload@[1:1] (line:column), expected false or true or null or {...} or [...] or number but was , while reading `payload`as Json.
 
1| 
   ^, while writing Json.
 
1| 
   ^" evaluating expression: "output application/json ---
{
 payload: payload,
 attributes: attributes
}".
	at org.mule.runtime.core.internal.el.dataweave.DataWeaveExpressionLanguageAdaptor.evaluate(DataWeaveExpressionLanguageAdaptor.java:205)
	at

**Comment by mfedorov** [comment]
1.0.2 is what we are using

**Comment by salumiahsyed** [comment]
Mule 4:
--------
Step 1: create a variable using mimeType text/plain

<set-variable value="#[payload]" doc:name="vRequestPayload" doc:id="3fb34e69-0332-4cf8-af66-ea5d07eda6a8" variableName="vRequestPayloadSize" mimeType="text/plain"/>

Step 2: use variable where ever required
"vAuditPayload": if (vars.vRequestPayloadSize == '') (app.name ++ ' request received')  else payload

**Comment by sanjukta-maji** [comment]
@salumiahsyed  this works !! thanks
