### ISSUE TITLE
request for support and a new user for external Maven clients

### ISSUE THREAD

**Issue by GeraldLoeffler** [mulesoft-consulting/json-logger#7]
Training is currently developing a new "Advanced Developer" course, and as part of that we're depending on the Mule4-version of this `json-logger` by downloading it as a Maven dependency from the Services Exchange, as indicated in your README. This works fine. However, it means that students attending a delivery of this Training course (i.e., customers) will need to configure their Maven builds accordingly. This has 2 repercussions:

1. It means that we as Training must be able to rely on the `json-logger` being *available from the Services Exchange at all times* - otherwise deliveries of this course will fail. Can we rely on this?

2. Students should ideally use separate credentials to authenticate agains the Services Exchange Maven facade (i.e., better not `guest-mule`?) with minimal privileges (the "Exchange Viewer" Anypoint Platform role is sufficient): if you agree then please *create such an Anypoint Platform user*.

**Comment by GeraldLoeffler** [comment]
just saw your blog article at https://blogs.mulesoft.com/dev/anypoint-platform-dev/json-logging-mule-4/ and have noted that you've already published Services Exchange credentials (`guest-mule`) to the world, so i suppose both of my requests above don't need any action?

**Comment by skuller** [comment]
hey @GeraldLoeffler, if it's for training I would suggest having assets like this in your own Training Exchange so that you can better handle it's access and lifecycle but to your point, yes guest-mule is an exchange view only user and unless I'm shown the door, my Exchange should be up and running for the time being :)
